services:
  mysql_events:
    image: mysql:8.0
    container_name: mysql_events
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
    ports:
      - "3306:3306"

  eventsapp:
    image: nourxgh/eventsproject:1.0.0
    container_name: events_project
    depends_on:
      - mysql_events
    ports:
      - "8089:8089"
