services:
  mysql_events:
    image: mysql:8.0
    container_name: mysql_events
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
    ports:
      - "3306:3306"

  eventsapp:
    image: nourxgh/eventsproject:1.0.0
    container_name: events_project
    depends_on:
      - mysql_events
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_events:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"

